#!/usr/bin/env bash
# Regenerate solo-engine.js from server.js.
# solo-engine.js runs the REAL server.js game logic in the browser behind tiny
# Node shims, so single-player solo mode stays perfectly in sync with multiplayer.
# Re-run this whenever server.js changes.
set -euo pipefail
cd "$(dirname "$0")"

OUT=solo-engine.js

cat > "$OUT" <<'HEADER'
// ─────────────────────────────────────────────────────────────────────────
// solo-engine.js — GENERATED by build-solo.sh. DO NOT EDIT BY HAND.
// It wraps server.js verbatim in browser shims so the authoritative game
// simulation runs client-side for solo (no-server) play. Bots and the human
// connect as ordinary WebSocket-style clients (see solo.js).
// ─────────────────────────────────────────────────────────────────────────
(function () {
  // Fake server-side socket for one participant (human or bot).
  function FakeServerWS() { this.readyState = 1; this._h = {}; this.onOut = null; }
  FakeServerWS.prototype.on   = function (t, cb) { this._h[t] = cb; };
  FakeServerWS.prototype.emit = function (t, a) { if (this._h[t]) this._h[t](a); };   // client → server
  FakeServerWS.prototype.send = function (json) { if (this.onOut) this.onOut(json); }; // server → client
  FakeServerWS.prototype.close = function () { this.readyState = 3; if (this._h.close) this._h.close(); };

  function FakeWSS() { this.clients = new Set(); this._h = {}; }
  FakeWSS.prototype.on = function (t, cb) { this._h[t] = cb; };

  var __wss = null;
  function require(m) {
    if (m === "ws")   return { WebSocketServer: function () { __wss = new FakeWSS(); return __wss; } };
    if (m === "http") return { createServer: function () { return { listen: function (_p, cb) { if (cb) cb(); } }; } };
    if (m === "fs")   return { readFile: function (_p, cb) { if (cb) cb(new Error("no fs in browser")); } };
    if (m === "path") return { join: function () { return Array.prototype.join.call(arguments, "/"); } };
    return {};
  }
  var process = { env: {} };
  var __dirname = "";

  // ===================== server.js (verbatim) =====================
HEADER

cat server.js >> "$OUT"

cat >> "$OUT" <<'FOOTER'
  // =================== end server.js (verbatim) ===================

  // Add a participant: returns their fake server-side socket. Calling code
  // wires sw.onOut (server→participant) and sw.emit("message", json) (participant→server).
  function makeConn() {
    var sw = new FakeServerWS();
    __wss.clients.add(sw);
    if (__wss._h.connection) __wss._h.connection(sw);
    return sw;
  }
  // Expose the authoritative wall/obstacle collision test (uses the current
  // map's geometry, swapped on round start) so bots can avoid walls.
  window.__ForsakenSolo = {
    makeConn: makeConn,
    blocked: function (x, y, r) { return positionBlocked(x, y, r); },
    mapSize: function () { return { w: MAP.w, h: MAP.h }; },
  };
})();
FOOTER

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
