// ─────────────────────────────────────────────────────────────────────────
// solo-engine.js — GENERATED by build-solo.sh. DO NOT EDIT BY HAND.
// It wraps server.js verbatim in browser shims so the authoritative game
// simulation runs client-side for solo (no-server) play. Bots and the human
// connect as ordinary WebSocket-style clients (see solo.js).
// ─────────────────────────────────────────────────────────────────────────
(function () {
  // Fake server-side socket for one participant (human or bot).
  function FakeServerWS() { this.readyState = 1; this._h = {}; this.onOut = null; }
  FakeServerWS.prototype.on   = function (t, cb) { this._h[t] = cb; };
  FakeServerWS.prototype.emit = function (t, a) { if (this._h[t]) this._h[t](a); };   // client → server
  FakeServerWS.prototype.send = function (json) { if (this.onOut) this.onOut(json); }; // server → client
  FakeServerWS.prototype.close = function () { this.readyState = 3; if (this._h.close) this._h.close(); };

  function FakeWSS() { this.clients = new Set(); this._h = {}; }
  FakeWSS.prototype.on = function (t, cb) { this._h[t] = cb; };

  var __wss = null;
  function require(m) {
    if (m === "ws")   return { WebSocketServer: function () { __wss = new FakeWSS(); return __wss; } };
    if (m === "http") return { createServer: function () { return { listen: function (_p, cb) { if (cb) cb(); } }; } };
    if (m === "fs")   return { readFile: function (_p, cb) { if (cb) cb(new Error("no fs in browser")); } };
    if (m === "path") return { join: function () { return Array.prototype.join.call(arguments, "/"); } };
    return {};
  }
  var process = { env: {} };
  var __dirname = "";

  // ===================== server.js (verbatim) =====================
// Forsaken — browser multiplayer server.
// Authoritative: roster, roles, generator progress, HP, ability cooldowns,
//                projectile motion, attack outcomes, round timer, win condition.
// Trusts: client positions (and client classification of its own skill check).
// Stamina is client-side state — used only as a gate on sprint speed locally.

const http = require("http");
const fs = require("fs");
const path = require("path");
const { WebSocketServer } = require("ws");

const PORT = process.env.PORT || 8080;
const TICK_MS = 50;

const MAP = { w: 2400, h: 1600 };
const WALL_T = 30;
// Each map has its own gen-spawn pool — only GENS_PER_ROUND of the
// configured pool spawn per round.
const CIRCUS_GEN_POOL = [
  { x: MAP.w * 0.12, y: MAP.h * 0.15 },
  { x: MAP.w * 0.88, y: MAP.h * 0.15 },
  { x: MAP.w * 0.12, y: MAP.h * 0.85 },
  { x: MAP.w * 0.88, y: MAP.h * 0.85 },
  { x: MAP.w * 0.50, y: MAP.h * 0.13 },
  { x: MAP.w * 0.50, y: MAP.h * 0.87 },
  { x: MAP.w * 0.10, y: MAP.h * 0.50 },
  { x: MAP.w * 0.90, y: MAP.h * 0.50 },
  { x: MAP.w * 0.28, y: MAP.h * 0.32 },
  { x: MAP.w * 0.72, y: MAP.h * 0.32 },
  { x: MAP.w * 0.28, y: MAP.h * 0.71 },
  { x: MAP.w * 0.72, y: MAP.h * 0.71 },
  { x: MAP.w * 0.40, y: MAP.h * 0.42 },
  { x: MAP.w * 0.60, y: MAP.h * 0.42 },
  { x: MAP.w * 0.40, y: MAP.h * 0.58 },
  { x: MAP.w * 0.60, y: MAP.h * 0.58 },
];
// Factory gens: tucked into the clear pockets of the factory maze
// (between walls and below the top conveyor / above the bottom conveyor).
const FACTORY_GEN_POOL = [
  { x: 200,  y: 240 },
  { x: 1000, y: 240 },
  { x: 1400, y: 240 },
  { x: 2200, y: 240 },
  { x: 200,  y: 1360 },
  { x: 1000, y: 1360 },
  { x: 1400, y: 1360 },
  { x: 2200, y: 1360 },
  { x: 200,  y: 700 },
  { x: 1000, y: 800 },
  { x: 1400, y: 800 },
  { x: 2200, y: 700 },
  { x: 600,  y: 1100 },
  { x: 1900, y: 1100 },
  { x: 700,  y: 500 },
  { x: 1700, y: 500 },
];
const GENS_PER_ROUND = 5;

// Walls and obstacles — duplicated from client so the server can resolve
// sniper-projectile collisions authoritatively. Must stay in sync with
// the client's WALLS / OBSTACLES / CONVEYORS arrays for each map.
const CIRCUS_WALLS = [
  { x: MAP.w / 2, y: WALL_T / 2, w: MAP.w, h: WALL_T },
  { x: MAP.w / 2, y: MAP.h - WALL_T / 2, w: MAP.w, h: WALL_T },
  { x: WALL_T / 2, y: MAP.h / 2, w: WALL_T, h: MAP.h },
  { x: MAP.w - WALL_T / 2, y: MAP.h / 2, w: WALL_T, h: MAP.h },
  { x: MAP.w / 2, y: MAP.h * 0.25, w: MAP.w * 0.55, h: WALL_T },
  { x: MAP.w / 2, y: MAP.h * 0.75, w: MAP.w * 0.55, h: WALL_T },
  { x: MAP.w / 3,     y: MAP.h / 2, w: WALL_T, h: MAP.h * 0.33 },
  { x: 2 * MAP.w / 3, y: MAP.h / 2, w: WALL_T, h: MAP.h * 0.33 },
  // Maze interior — symmetric about both axes.
  { x: 550,  y: 250,  w: WALL_T, h: 280 },
  { x: 1850, y: 250,  w: WALL_T, h: 280 },
  { x: 550,  y: 1350, w: WALL_T, h: 280 },
  { x: 1850, y: 1350, w: WALL_T, h: 280 },
  { x: 950,  y: 230,  w: WALL_T, h: 320 },
  { x: 1450, y: 230,  w: WALL_T, h: 320 },
  { x: 950,  y: 1370, w: WALL_T, h: 320 },
  { x: 1450, y: 1370, w: WALL_T, h: 320 },
  { x: 700,  y: 600,  w: 280,    h: WALL_T },
  { x: 1700, y: 600,  w: 280,    h: WALL_T },
  { x: 700,  y: 1000, w: 280,    h: WALL_T },
  { x: 1700, y: 1000, w: 280,    h: WALL_T },
];
// Factory map — dense maze with conveyor belts. Vertical walls all sit
// between y=300 and y=1300 so the top and bottom corridors stay clear
// for the belts.
const FACTORY_WALLS = [
  { x: MAP.w / 2, y: WALL_T / 2, w: MAP.w, h: WALL_T },
  { x: MAP.w / 2, y: MAP.h - WALL_T / 2, w: MAP.w, h: WALL_T },
  { x: WALL_T / 2, y: MAP.h / 2, w: WALL_T, h: MAP.h },
  { x: MAP.w - WALL_T / 2, y: MAP.h / 2, w: WALL_T, h: MAP.h },
  // Vertical maze walls
  { x: 400,  y: 450,  w: WALL_T, h: 300 },
  { x: 400,  y: 950,  w: WALL_T, h: 300 },
  { x: 800,  y: 700,  w: WALL_T, h: 400 },
  { x: 800,  y: 1200, w: WALL_T, h: 200 },
  { x: 1200, y: 400,  w: WALL_T, h: 200 },
  { x: 1200, y: 900,  w: WALL_T, h: 600 },
  { x: 1600, y: 700,  w: WALL_T, h: 400 },
  { x: 1600, y: 1200, w: WALL_T, h: 200 },
  { x: 2000, y: 450,  w: WALL_T, h: 300 },
  { x: 2000, y: 950,  w: WALL_T, h: 300 },
  // Horizontal maze walls
  { x: 600,  y: 600,  w: 380, h: WALL_T },
  { x: 1400, y: 600,  w: 380, h: WALL_T },
  { x: 1000, y: 1000, w: 380, h: WALL_T },
  { x: 1800, y: 1000, w: 380, h: WALL_T },
  { x: 400,  y: 800,  w: 600, h: WALL_T },
  { x: 2000, y: 800,  w: 600, h: WALL_T },
  { x: 600,  y: 1200, w: 280, h: WALL_T },
  { x: 1800, y: 400,  w: 280, h: WALL_T },
];
// Conveyors: { x, y, w, h, vx, vy } — pushes any entity standing inside.
const FACTORY_CONVEYORS = [
  // Top east-bound belt (full-width top corridor, y < 200 is clear)
  { x: MAP.w / 2, y: 150, w: 2200, h: 80, vx: 110, vy: 0 },
  // Bottom west-bound belt
  { x: MAP.w / 2, y: MAP.h - 150, w: 2200, h: 80, vx: -110, vy: 0 },
];
const CIRCUS_OBSTACLES = [
  { x: 300,  y: 360,  w: 50, h: 50 },
  { x: 560,  y: 300,  w: 50, h: 50 },
  { x: 200,  y: 180,  w: 36, h: 36 },
  { x: 700,  y: 200,  w: 32, h: 70 },
  { x: MAP.w - 300, y: 360, w: 50, h: 50 },
  { x: MAP.w - 560, y: 300, w: 50, h: 50 },
  { x: MAP.w - 200, y: 180, w: 36, h: 36 },
  { x: MAP.w - 700, y: 200, w: 32, h: 70 },
  { x: 300,  y: MAP.h - 360, w: 50, h: 50 },
  { x: 560,  y: MAP.h - 300, w: 50, h: 50 },
  { x: 200,  y: MAP.h - 180, w: 36, h: 36 },
  { x: 700,  y: MAP.h - 200, w: 32, h: 70 },
  { x: MAP.w - 300, y: MAP.h - 360, w: 50, h: 50 },
  { x: MAP.w - 560, y: MAP.h - 300, w: 50, h: 50 },
  { x: MAP.w - 200, y: MAP.h - 180, w: 36, h: 36 },
  { x: MAP.w - 700, y: MAP.h - 200, w: 32, h: 70 },
  { x: MAP.w / 2,    y: MAP.h * 0.38, w: 50, h: 50 },
  { x: MAP.w / 2,    y: MAP.h * 0.62, w: 50, h: 50 },
  { x: MAP.w * 0.42, y: MAP.h / 2,    w: 50, h: 50 },
  { x: MAP.w * 0.58, y: MAP.h / 2,    w: 50, h: 50 },
  { x: MAP.w * 0.3,  y: MAP.h / 2,    w: 36, h: 36 },
  { x: MAP.w * 0.7,  y: MAP.h / 2,    w: 36, h: 36 },
];
// Factory obstacles: scattered industrial props in the corridors and
// rooms. Types reused (crate / barrel / locker) — client rerenders them
// with an industrial palette when G.mapId === "factory".
const FACTORY_OBSTACLES = [
  { x: 300,  y: 240,  w: 50, h: 50 },
  { x: 2100, y: 240,  w: 50, h: 50 },
  { x: 300,  y: 1360, w: 50, h: 50 },
  { x: 2100, y: 1360, w: 50, h: 50 },
  { x: 500,  y: 700,  w: 36, h: 36 },
  { x: 1900, y: 700,  w: 36, h: 36 },
  { x: 500,  y: 1000, w: 32, h: 70 },
  { x: 1900, y: 1000, w: 32, h: 70 },
  { x: 1100, y: 350,  w: 50, h: 50 },
  { x: 1300, y: 350,  w: 50, h: 50 },
  { x: 1100, y: 1250, w: 36, h: 36 },
  { x: 1300, y: 1250, w: 36, h: 36 },
  { x: 250,  y: 1100, w: 50, h: 50 },
  { x: 2150, y: 1100, w: 50, h: 50 },
];
const MAPS = {
  circus:  { walls: CIRCUS_WALLS,  obstacles: CIRCUS_OBSTACLES,  gens: CIRCUS_GEN_POOL,  conveyors: [] },
  factory: { walls: FACTORY_WALLS, obstacles: FACTORY_OBSTACLES, gens: FACTORY_GEN_POOL, conveyors: FACTORY_CONVEYORS },
};
const MAP_IDS = Object.keys(MAPS);
// Active map references — reassigned in startRound. The helper functions
// below (positionBlocked, etc.) read from WALLS / OBSTACLES / CONVEYORS.
let WALLS = CIRCUS_WALLS;
let OBSTACLES = CIRCUS_OBSTACLES;
let GEN_POOL = CIRCUS_GEN_POOL;
let CONVEYORS = [];

function pointInRect(x, y, r) {
  return x >= r.x - r.w / 2 && x <= r.x + r.w / 2 &&
         y >= r.y - r.h / 2 && y <= r.y + r.h / 2;
}
// True if a circle of radius r centered at (cx, cy) overlaps the rect.
function circleRectOverlap(cx, cy, r, rect) {
  const left = rect.x - rect.w / 2, right = rect.x + rect.w / 2;
  const top = rect.y - rect.h / 2, bottom = rect.y + rect.h / 2;
  const px = cx < left ? left : (cx > right ? right : cx);
  const py = cy < top ? top : (cy > bottom ? bottom : cy);
  const dx = cx - px, dy = cy - py;
  return (dx * dx + dy * dy) < r * r;
}
function positionBlocked(x, y, r) {
  for (const w of WALLS) if (circleRectOverlap(x, y, r, w)) return true;
  for (const o of OBSTACLES) if (circleRectOverlap(x, y, r, o)) return true;
  return false;
}

// ---- Characters ----
const SURVIVOR_CHARS = [
  { id: "runner",   name: "Runner",   color: "#ff80c0", speedMult: 1.10, repairMult: 1.00, blurb: "+10% speed" },
  { id: "engineer", name: "Engineer", color: "#ffd84a", speedMult: 1.00, repairMult: 1.30, blurb: "+30% repair" },
  { id: "scout",    name: "Scout",    color: "#6cb6ff", speedMult: 1.05, repairMult: 1.05, blurb: "balanced" },
  { id: "sentinel", name: "Frost Knight", color: "#4ad0c0", speedMult: 1.00, repairMult: 0.95, blurb: "slows the killer" },
  { id: "sniper",   name: "Sniper",   color: "#a070f0", speedMult: 0.98, repairMult: 0.95, blurb: "stuns the killer" },
  { id: "fencer",   name: "Fencer",   color: "#d04050", speedMult: 1.00, repairMult: 1.00, blurb: "melee stun + soda heal" },
  { id: "kacey",    name: "Kacey",    color: "#ff9050", speedMult: 1.00, repairMult: 1.00, blurb: "cat — burger + meow heals" },
  { id: "angel",    name: "Angel",    color: "#3a1860", speedMult: 1.00, repairMult: 1.00, blurb: "shady — dagger + duck + spawn pad" },
  { id: "pollen",   name: "Pollen",   color: "#4a8c40", speedMult: 1.00, repairMult: 1.00, blurb: "clover trail + healing / defence fountains" },
];
const KILLER_CHARS = [
  { id: "slasher", name: "Slasher", color: "#e94560", speedMult: 1.00, attackRadius: 70,  attackDamage: 17, attackName: "Knife Slash",  attackCooldown: 1.0, blurb: "balanced reach" },
  { id: "stalker", name: "Stalker", color: "#7a2030", speedMult: 0.92, attackRadius: 110, attackDamage: 13, attackName: "Claw Strike", attackCooldown: 1.3, blurb: "long reach, slower, lower dmg" },
  { id: "lunar",   name: "Lunar",   color: "#9070ff", speedMult: 1.00, attackRadius: 80,  attackDamage: 15, attackName: "Punch",       attackCooldown: 1.0, blurb: "portals & teleport" },
  { id: "sly",     name: "Sly",     color: "#3a2a4a", speedMult: 1.00, attackRadius: 75,  attackDamage: 14, attackName: "Strike",      attackCooldown: 1.0, blurb: "human / dino shapeshifter",
    // Dino-form overrides. Speed is much lower but damage and reach climb,
    // and the client lets him phase through interior walls / obstacles.
    speedMultDino: 1.1, attackDamageDino: 21, attackRadiusDino: 150 },
];

// ---- HP ----
const SURVIVOR_HP_MAX = 100;

// ---- Abilities ----
// type drives applyAbility's switch. cd is in seconds.
const ABILITIES = {
  runner: [
    { id: "dash",  name: "Dash",       cd: 8,  type: "speed_self",  mult: 2.5,   duration: 0.8 },
    { id: "smoke", name: "Smoke Bomb", cd: 20, type: "smoke",       radius: 260, duration: 3.5 },
  ],
  sentinel: [
    { id: "burst", name: "Stun Burst", cd: 12, type: "stun_burst",  radius: 180, slowMult: 0.50, duration: 10.0 },
    // Slow Field persists until the killer attacks it (or the round ends).
    // Capped at maxFields per Sentinel — placing a new one pops the oldest.
    // channelDuration is the summoning channel before the field drops.
    { id: "field", name: "Snow Field", cd: 18, type: "slow_field",  radius: 220, slowMult: 0.60, duration: 20, channelDuration: 0.7, maxFields: 3 },
  ],
  fencer: [
    // Slash: melee swing in front of the fencer. Stuns the killer for
    // stunDuration seconds if any is within range — no damage.
    { id: "slash", name: "Slash", cd: 25, type: "slash_stun", range: 80, stunDuration: 5 },
    // Soda: heals 30 HP over 10s. Limited to maxUses casts per round.
    { id: "soda",  name: "Soda",  cd: 30, type: "heal_self",  amount: 30, duration: 10, maxUses: 3 },
  ],
  kacey: [
    // Burger: throw a healing burger in the facing direction. It slows
    // down with friction, bounces off walls/obstacles, and heals any
    // OTHER survivor that touches it. Despawns on pickup or after TTL.
    { id: "burger", name: "Burger!", cd: 18, type: "throw_burger", speed: 500, healAmount: 25, ttl: 30, bounce: 0.6 },
    // Meow: short-range aoe. Heals every survivor within radius and
    // applies a light slow (0.9x) to any killer within radius.
    { id: "meow",   name: "MEOW!",  cd: 35, type: "meow", radius: 600, healAmount: 20, slowMult: 0.9, slowDuration: 4 },
  ],
  sniper: [
    // Shoot: must be aimed by the client and consumes 1 ammo. Projectile
    // travels in the supplied aim direction, breaks on the first wall or
    // obstacle, and stuns the killer for stunDuration seconds on hit.
    // range is effectively unlimited — the bullet only stops on a wall,
    // obstacle, or the outer map boundary (handled in the tick loop).
    { id: "shoot",  name: "Shoot",  cd: 25, type: "shoot_sniper", speed: 1100, range: 99999, stunDuration: 10, hitRadius: 30 },
    // Reload: 5s channel before ammo refills. Only usable at 0 ammo.
    { id: "reload", name: "Reload", cd: 20, type: "reload_sniper", reloadDuration: 5.0 },
    // Sneak: turns the Sniper mostly invisible to everyone for a few seconds.
    { id: "sneak",  name: "Sneak",  cd: 20, type: "sneak", duration: 6.0 },
  ],
  engineer: [
    // Shield: 6s of damage immunity, but you move at 0.6x speed while it's up.
    { id: "shield", name: "Shield", cd: 20, type: "shield", duration: 6.0, speedMult: 0.6 },
    // Robot: 3s rooted build, then a robot trundles toward the killer at walk
    // speed. Touches them -> 12s stun. Self-destructs after 40s if it doesn't
    // catch them. Only one robot per Engineer at a time.
    { id: "robot",  name: "Robot",  cd: 50, type: "spawn_robot", channelDuration: 3.0, speed: 100, hitRadius: 25, stunDuration: 12, ttl: 25 },
  ],
  scout: [
    { id: "rally", name: "Rally", cd: 14, type: "speed_team", mult: 1.25, radius: 200, duration: 4.0 },
    { id: "scan",  name: "Scan",  cd: 12, type: "reveal",     duration: 2.0 },
  ],
  angel: [
    // Stab: short-range dagger. Stuns the killer 3s on hit (no damage),
    // grants 20% malice (40% if currently ducking).
    { id: "stab",    name: "Stab",    cd: 8,  type: "stab", range: 80, stunDuration: 3, maliceGain: 20, maliceGainDuck: 40 },
    // Duck: 95% invis + 0.6x speed for 7s. No reveal-on-attack — Angel can
    // stab from inside the duck for the malice bonus.
    { id: "duck",    name: "Duck",    cd: 18, type: "duck", duration: 7.0, speedMult: 0.6 },
    // Spawner: 3s channel, places one spawn pad. Locked after first use
    // (handled via maxUses). The pad is what the passive respawns on.
    { id: "spawner", name: "Spawner", cd: 60, type: "spawn_pad", channelDuration: 3.0, maxUses: 1 },
  ],
  pollen: [
    // Breathe: instant self-heal.
    { id: "breathe", name: "Breathe", cd: 20, type: "heal_self_instant", amount: 10 },
    // Heal Station: 5s channel, costs 15 HP up front, drops a fountain
    // that heals nearby survivors 2 HP/sec until a killer melee breaks it.
    { id: "heal_station", name: "Heal Station", cd: 30, type: "build_station",
      stationKind: "heal", channelDuration: 5.0, hpCost: 15, radius: 140,
      healPerSec: 2 },
    // Defence Station: 5s channel + 15 HP cost like Heal Station, but
    // refreshes a short shield on any survivor inside the radius.
    { id: "defence_station", name: "Defence Station", cd: 30, type: "build_station",
      stationKind: "defence", channelDuration: 5.0, hpCost: 15, radius: 140,
      shieldDuration: 8 },
  ],
  slasher: [
    { id: "throw",  name: "Throw Knife", cd: 5,  type: "projectile", damage: 12, speed: 700, range: 700 },
    { id: "frenzy", name: "Frenzy",      cd: 14, type: "speed_self", mult: 1.30, duration: 4.0 },
  ],
  stalker: [
    { id: "step",  name: "Shadow Step", cd: 6,  type: "teleport",    distance: 220 },
    { id: "stalk", name: "Stalk",       cd: 15, type: "buff_attack", multiplier: 2, duration: 4.0 },
  ],
  sly: [
    // Slot 0 — Trap when human, FIRE!! when dino. Server dispatches by form.
    { id: "trap_fire", name: "Trap", cd: 15, type: "trap_fire",
      trapCD: 15, fireCD: 3,
      trapStunDuration: 4, maxTraps: 3,
      fireSpeed: 700, fireRange: 800, fireDamage: 10 },
    // Slot 1 — Transform: 5s rooted channel, then dino for 20s, then revert.
    { id: "transform", name: "Transform", cd: 40, type: "transform",
      channelDuration: 5.0, duration: 20.0 },
  ],
  lunar: [
    // Build Portal: 4s rooted channel, drops a portal at the killer's
    // position when the channel completes. Cap at maxPortals — placing a
    // 4th evicts the oldest.
    { id: "build_portal", name: "Build Portal", cd: 15, type: "build_portal", channelDuration: 4.0, maxPortals: 3 },
    // Teleport Portal: opens the portal menu with color-coded portals
    // (green/yellow/red by nearest survivor distance — that's the scan
    // info, now baked in). When the killer picks a portal the client
    // sends this ability with portalId; server validates, channels for
    // channelDuration, then teleports the killer. The bar's Back button
    // simply closes the menu without spending the CD.
    { id: "teleport_portal", name: "Teleport", cd: 20, type: "teleport_portal", channelDuration: 2.0 },
    // Dash: 3s speed boost; the first survivor Lunar collides with during
    // the dash takes hitDamage and is slowed to hitSlowMult for hitSlowDuration.
    { id: "dash", name: "Dash", cd: 20, type: "dash_strike", duration: 3.0, speedMult: 1.8, hitDamage: 30, hitSlowMult: 0.7, hitSlowDuration: 3.0 },
  ],
};

// ---- Round ----
const ROUND_DURATION = 360;   // 6 minutes
const TIME_PER_GEN = -20;
const TIME_PER_DOWN = +25;
const RESULT_HOLD_MS = 5000;

// ---- Skill check ----
const SKILL_PROGRESS = { green: 0.13, yellow: 0.05, red: -0.10 };
const SKILL_NEAR_RADIUS = 90;
const SKILL_COOLDOWN_MS = 400;

const state = {
  phase: "lobby",
  players: new Map(),
  generators: freshGens(),
  designatedKillerId: null,
  hostClientId: null,           // persistent id of the host, so they can reclaim on rejoin
  randomKillerEnabled: false,
  selectedMap: "random",        // "random" | "circus" | "factory"
  roundTimer: ROUND_DURATION,
  winner: null,
  resetAt: 0,
  lastSkill: new Map(),
  projectiles: [],
  smokes: [],
  slowFields: [],
  portals: [],
  burgers: [],
  robots: [],
  traps: [],
  spawnPads: [],
  clovers: [],     // Pollen's clover trail
  stations: [],    // Pollen's heal + defence stations
  nextEntityId: 1,
};

function freshGens() {
  // Fisher–Yates shuffle the pool, then take the first GENS_PER_ROUND entries.
  const idx = GEN_POOL.map((_, i) => i);
  for (let i = idx.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [idx[i], idx[j]] = [idx[j], idx[i]];
  }
  return idx.slice(0, GENS_PER_ROUND).map(k => {
    const p = GEN_POOL[k];
    return { x: p.x, y: p.y, progress: 0, done: false };
  });
}

// ---------- HTTP ----------
const server = http.createServer((req, res) => {
  const url = req.url.split("?")[0];
  if (url === "/" || url === "/index.html") {
    return sendFile(res, "index.html", "text/html; charset=utf-8");
  }
  if (url === "/health") { res.writeHead(200); res.end("ok"); return; }
  if (url.startsWith("/music/")) {
    const file = url.slice("/music/".length);
    if (!/^[a-zA-Z0-9_]+\.(mp3|wav)$/.test(file)) {
      res.writeHead(400); res.end("bad name"); return;
    }
    const type = file.endsWith(".wav") ? "audio/wav" : "audio/mpeg";
    return sendFile(res, path.join("music", file), type, "public, max-age=86400");
  }
  if (url.startsWith("/sounds/")) {
    const file = url.slice("/sounds/".length);
    if (!/^[a-zA-Z0-9_]+\.(mp3|wav)$/.test(file)) {
      res.writeHead(400); res.end("bad name"); return;
    }
    const type = file.endsWith(".wav") ? "audio/wav" : "audio/mpeg";
    return sendFile(res, path.join("sounds", file), type, "public, max-age=86400");
  }
  if (url.startsWith("/images/")) {
    const file = url.slice("/images/".length);
    if (!/^[a-zA-Z0-9_\-]+\.(png|jpg|jpeg|gif|webp)$/.test(file)) {
      res.writeHead(400); res.end("bad name"); return;
    }
    const ext = file.split(".").pop().toLowerCase();
    const type = ext === "png"  ? "image/png"
              : ext === "gif"   ? "image/gif"
              : ext === "webp"  ? "image/webp"
                                : "image/jpeg";
    return sendFile(res, path.join("images", file), type, "public, max-age=86400");
  }
  if (url === "/chars") {
    res.writeHead(200, { "Content-Type": "application/json", "Cache-Control": "no-store" });
    res.end(JSON.stringify({
      survivorChars: SURVIVOR_CHARS,
      killerChars: KILLER_CHARS,
      abilities: ABILITIES,
      survivorHpMax: SURVIVOR_HP_MAX,
      roundDuration: ROUND_DURATION,
    }));
    return;
  }
  if (url === "/custom-art.js") {
    return sendFile(res, "custom-art.js", "application/javascript; charset=utf-8");
  }
  res.writeHead(404); res.end("not found");
});
function sendFile(res, name, type, cache) {
  fs.readFile(path.join(__dirname, name), (err, data) => {
    if (err) { res.writeHead(err.code === "ENOENT" ? 404 : 500); res.end(); return; }
    res.writeHead(200, {
      "Content-Type": type,
      "Cache-Control": cache || "no-store",
      "Content-Length": data.length,
    });
    res.end(data);
  });
}

// ---------- WS ----------
const wss = new WebSocketServer({ server });
let nextId = 1;

wss.on("connection", (ws) => {
  const id = nextId++;
  ws.playerId = id;
  ws.on("message", (raw) => {
    let msg; try { msg = JSON.parse(raw); } catch { return; }
    handle(id, ws, msg);
  });
  ws.on("close", () => removePlayer(id));
  ws.on("error", () => {});
});

function handle(id, ws, msg) {
  switch (msg.type) {
    case "join":      return onJoin(id, ws, msg);
    case "pick_char": return onPickChar(id, msg);
    case "designate": return onDesignate(id, msg);
    case "toggle_random_killer": return onToggleRandomKiller(id, msg);
    case "set_map":   return onSetMap(id, msg);
    case "start":     return onStart(id);
    case "pos":       return onPos(id, msg);
    case "attack":    return onAttack(id);
    case "ability":   return onAbility(id, msg);
    case "dash_wall_hit": return onDashWallHit(id);
    case "skill":     return onSkill(id, msg);
    case "leave":     return removePlayer(id);
  }
}

function onJoin(id, ws, msg) {
  const name = (msg.name || "Player").toString().slice(0, 16);
  const clientId = (msg.clientId != null) ? String(msg.clientId).slice(0, 64) : null;
  const anyHost = [...state.players.values()].some(p => p.isHost);
  // Host goes to the returning host (matching clientId), or to the first player
  // when nobody is host yet.
  const isHost = (clientId && clientId === state.hostClientId) || state.players.size === 0 || !anyHost;
  if (isHost) {
    for (const p of state.players.values()) p.isHost = false;   // demote any stand-in host
    state.hostClientId = clientId;
  }
  const player = {
    id, ws, name, clientId,
    role: "unassigned",
    survivorChar: "scout",
    killerChar: "slasher",
    color: SURVIVOR_CHARS.find(c => c.id === "scout").color,
    x: MAP.w / 2, y: MAP.h - 200,
    facing: { x: 1, y: 0 },
    alive: true,
    hp: SURVIVOR_HP_MAX,
    cooldowns: [0, 0, 0],     // ms epoch when ability slot becomes ready
    mainAttackCdUntil: 0,
    ammo: 1,                  // sniper-specific; harmless on other chars
    reloadUntil: 0,
    effects: freshEffects(),
    isHost,
    joinedAt: Date.now(),
  };
  state.players.set(id, player);
  send(ws, {
    type: "welcome",
    id, map: MAP, gens: state.generators,
    survivorChars: SURVIVOR_CHARS,
    killerChars: KILLER_CHARS,
    abilities: ABILITIES,
    roundDuration: ROUND_DURATION,
    survivorHpMax: SURVIVOR_HP_MAX,
  });
  broadcastLobby();
}

function freshEffects() {
  return {
    speedMult: 1, speedUntil: 0,
    healUntil: 0, healRate: 0,
    stalkUntil: 0,
    revealedUntil: 0,
    slowMult: 1, slowUntil: 0,
    sneakUntil: 0,
    duckUntil: 0,
    shieldUntil: 0,
    dashStrikeUntil: 0,
    dashHitDamage: 0,
    dashHitSlowMult: 1,
    dashHitSlowDuration: 0,
  };
}

function onPickChar(id, msg) {
  const p = state.players.get(id);
  if (!p) return;
  if (msg.survivorChar && SURVIVOR_CHARS.some(c => c.id === msg.survivorChar)) {
    p.survivorChar = msg.survivorChar;
  }
  if (msg.killerChar && KILLER_CHARS.some(c => c.id === msg.killerChar)) {
    p.killerChar = msg.killerChar;
  }
  if (state.phase === "lobby") {
    const sc = SURVIVOR_CHARS.find(c => c.id === p.survivorChar);
    p.color = sc.color;
  }
  broadcastLobby();
}

function onDesignate(id, msg) {
  const host = state.players.get(id);
  if (!host || !host.isHost) return;
  if (state.phase !== "lobby") return;
  if (state.randomKillerEnabled) return; // manual pick disabled while random is on
  if (msg.id === null || msg.id === 0) {
    state.designatedKillerId = null;
    broadcastLobby();
    return;
  }
  if (!state.players.has(msg.id)) return;
  state.designatedKillerId = msg.id;
  broadcastLobby();
}

function onToggleRandomKiller(id, msg) {
  const host = state.players.get(id);
  if (!host || !host.isHost) return;
  if (state.phase !== "lobby") return;
  state.randomKillerEnabled = !!msg.enabled;
  if (state.randomKillerEnabled) state.designatedKillerId = null;
  broadcastLobby();
}

function onSetMap(id, msg) {
  const host = state.players.get(id);
  if (!host || !host.isHost) return;
  if (state.phase !== "lobby") return;
  const m = msg && msg.map;
  if (m === "random" || MAP_IDS.includes(m)) {
    state.selectedMap = m;
    broadcastLobby();
  }
}

function removePlayer(id) {
  const p = state.players.get(id);
  if (!p) return;
  const wasHost = p.isHost;
  // If the killer drops mid-round, survivors auto-win.
  const killerLeftMidRound = state.phase === "playing" && p.role === "killer";
  state.players.delete(id);
  state.lastSkill.delete(id);
  state.projectiles = state.projectiles.filter(pr => pr.ownerId !== id);
  if (state.designatedKillerId === id) state.designatedKillerId = null;
  if (wasHost && state.players.size > 0) {
    const next = [...state.players.values()].sort((a, b) => a.joinedAt - b.joinedAt)[0];
    next.isHost = true;
  }
  if (killerLeftMidRound) {
    endRound("survivors");
  } else if (state.phase === "playing") {
    checkRoundEnd();
  }
  broadcastLobby();
}

function onStart(id) {
  if (state.phase !== "lobby") return;
  const p = state.players.get(id);
  if (!p || !p.isHost) return;
  if (state.players.size < 2) return;
  if (state.randomKillerEnabled) {
    // Roll a random player from the lobby as the killer.
    const ids = [...state.players.keys()];
    state.designatedKillerId = ids[Math.floor(Math.random() * ids.length)];
  } else {
    if (state.designatedKillerId === null) return;
    if (!state.players.has(state.designatedKillerId)) return;
  }
  startRound();
}

function onPos(id, msg) {
  const p = state.players.get(id);
  if (!p || state.phase !== "playing") return;
  if (!p.alive) return;
  if (typeof msg.x !== "number" || typeof msg.y !== "number") return;
  p.x = clamp(msg.x, 20, MAP.w - 20);
  p.y = clamp(msg.y, 20, MAP.h - 20);
  if (msg.facing && typeof msg.facing.x === "number") {
    p.facing = { x: msg.facing.x, y: msg.facing.y };
  }
}

function onAttack(id) {
  if (state.phase !== "playing") return;
  const a = state.players.get(id);
  if (!a || a.role !== "killer" || !a.alive) return;
  const kch = killerCharOf(a);
  const now = Date.now();
  if (now < (a.mainAttackCdUntil || 0)) return;
  a.mainAttackCdUntil = now + (kch.attackCooldown || 1.0) * 1000;
  const dino = (a.killerChar === "sly" && a.form === "dino");
  const reach = dino && kch.attackRadiusDino ? kch.attackRadiusDino : kch.attackRadius;
  let best = null, bestD = reach;
  for (const [pid, p] of state.players) {
    if (pid === id) continue;
    if (p.role !== "survivor" || !p.alive) continue;
    const d = Math.hypot(p.x - a.x, p.y - a.y);
    if (d < bestD) { bestD = d; best = p; }
  }
  if (best) {
    let dmg = (dino && kch.attackDamageDino) ? kch.attackDamageDino : kch.attackDamage;
    if (now < a.effects.stalkUntil) {
      dmg *= 2;
      a.effects.stalkUntil = 0; // consume
    }
    applyDamage(best, dmg, a);
  }
  // Killer's basic attack also shatters any slow field whose center
  // is within their attack reach.
  const brokenFields = [];
  state.slowFields = state.slowFields.filter(f => {
    if (Math.hypot(a.x - f.x, a.y - f.y) <= reach) {
      brokenFields.push({ id: f.id, x: f.x, y: f.y, radius: f.radius });
      return false;
    }
    return true;
  });
  if (brokenFields.length > 0) {
    broadcast({ type: "field_break", fields: brokenFields, by: a.id });
  }
  // Killer attack also smashes any Pollen station whose center is in reach.
  const brokenStations = [];
  state.stations = state.stations.filter(st => {
    if (Math.hypot(a.x - st.x, a.y - st.y) <= reach) {
      brokenStations.push({ id: st.id, x: st.x, y: st.y, kind: st.kind });
      return false;
    }
    return true;
  });
  if (brokenStations.length > 0) {
    broadcast({ type: "station_break", stations: brokenStations, by: a.id });
  }
}

function applyDamage(target, amount, attacker) {
  if (!target.alive) return;
  // Engineer shield: full damage immunity while active.
  if (Date.now() < (target.effects.shieldUntil || 0)) {
    broadcast({ type: "shield_block", id: target.id, by: attacker.id });
    return;
  }
  target.hp = Math.max(0, target.hp - amount);
  broadcast({
    type: "damage",
    id: target.id,
    hp: Math.round(target.hp),
    by: attacker.id,
    amount,
  });
  if (target.hp <= 0) {
    // Angel passive: at 100% malice with a spawn pad, the next lethal hit
    // sends Angel back to the pad at 65% HP with wings instead of going down.
    // Malice is consumed; pad stays. If no pad was placed, Angel dies normally.
    if (target.role === "survivor" && target.survivorChar === "angel"
        && (target.malice || 0) >= 100) {
      const pad = state.spawnPads.find(sp => sp.ownerId === target.id);
      if (pad) {
        target.hp = Math.round(SURVIVOR_HP_MAX * 0.65);
        target.x = pad.x;
        target.y = pad.y;
        target.malice = 0;
        target.respawned = true;
        broadcast({ type: "respawn", id: target.id, x: pad.x, y: pad.y, hp: target.hp });
        return;
      }
    }
    target.alive = false;
    state.roundTimer += TIME_PER_DOWN;
    broadcast({ type: "down", id: target.id, by: attacker.id, timer: state.roundTimer });
    checkRoundEnd();
  }
}

// Client reports that a dashing Lunar slammed into a wall. Stun for 2s
// and end the dash. Only valid while dashStrikeUntil is live, so the
// client can't trigger this outside an actual dash.
function onDashWallHit(id) {
  if (state.phase !== "playing") return;
  const p = state.players.get(id);
  if (!p || !p.alive) return;
  const now = Date.now();
  if (!p.effects.dashStrikeUntil || now >= p.effects.dashStrikeUntil) return;
  const STUN = 2.0;
  p.effects.dashStrikeUntil = 0;
  p.effects.speedUntil = 0;
  p.effects.speedMult  = 1;
  p.effects.slowMult   = 0.05;
  p.effects.slowUntil  = Math.max(p.effects.slowUntil || 0, now + STUN * 1000);
  broadcast({ type: "stun", id: p.id, by: p.id, duration: STUN });
}

function onAbility(id, msg) {
  if (state.phase !== "playing") return;
  const p = state.players.get(id);
  if (!p || !p.alive) return;
  const slot = msg.slot | 0;
  if (slot < 0 || slot > 2) return;
  const charId = p.role === "killer" ? p.killerChar : p.survivorChar;
  const list = ABILITIES[charId];
  if (!list || !list[slot]) return;
  const ab = list[slot];
  const now = Date.now();
  if (now < p.cooldowns[slot]) return;
  // Pre-validate sniper-specific resource gates BEFORE consuming the CD.
  if (ab.type === "shoot_sniper" && (p.ammo || 0) <= 0) return;
  if (ab.type === "reload_sniper") {
    if ((p.ammo || 0) >= 1) return;            // already loaded
    if (now < (p.reloadUntil || 0)) return;    // already reloading
  }
  if (ab.type === "spawn_robot") {
    // One robot per Engineer at a time.
    if (state.robots.some(r => r.ownerId === p.id)) return;
  }
  // Generic per-round use-limit (e.g. Fencer's Soda).
  if (ab.maxUses) {
    if (!p.abilityUses) p.abilityUses = {};
    const used = p.abilityUses[slot] || 0;
    if (used >= ab.maxUses) return;
    p.abilityUses[slot] = used + 1;
  }
  p.cooldowns[slot] = now + ab.cd * 1000;
  applyAbility(p, ab, slot, msg);
}

function applyAbility(p, ab, slot, msg) {
  const now = Date.now();
  switch (ab.type) {
    case "speed_self":
      p.effects.speedMult = ab.mult;
      p.effects.speedUntil = now + ab.duration * 1000;
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type, mult: ab.mult, duration: ab.duration });
      break;
    case "smoke":
      state.smokes.push({
        id: state.nextEntityId++,
        x: p.x, y: p.y,
        radius: ab.radius,
        ttl: ab.duration,
        ownerId: p.id,
      });
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type, x: p.x, y: p.y });
      break;
    case "gen_boost": {
      let bestIdx = -1, bestD = ab.range;
      for (let i = 0; i < state.generators.length; i++) {
        const g = state.generators[i];
        if (g.done) continue;
        const d = Math.hypot(g.x - p.x, g.y - p.y);
        if (d < bestD) { bestD = d; bestIdx = i; }
      }
      if (bestIdx >= 0) {
        const g = state.generators[bestIdx];
        g.progress = Math.min(1, g.progress + ab.amount);
        if (g.progress >= 1) {
          g.progress = 1; g.done = true;
          state.roundTimer = Math.max(0, state.roundTimer + TIME_PER_GEN);
          broadcast({ type: "gen_done", indices: [bestIdx], timer: state.roundTimer });
          if (state.roundTimer <= 0) endRound("survivors");
        }
      }
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type });
      break;
    }
    case "heal_self":
      p.effects.healUntil = now + ab.duration * 1000;
      p.effects.healRate = ab.amount / ab.duration;
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type, duration: ab.duration });
      break;
    case "speed_team": {
      const affected = [];
      for (const other of state.players.values()) {
        if (other.role !== "survivor" || !other.alive) continue;
        if (Math.hypot(other.x - p.x, other.y - p.y) <= ab.radius) {
          other.effects.speedMult = ab.mult;
          other.effects.speedUntil = now + ab.duration * 1000;
          affected.push(other.id);
        }
      }
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type, x: p.x, y: p.y, radius: ab.radius, affected });
      break;
    }
    case "reveal":
      for (const other of state.players.values()) {
        if (other.role === "killer") {
          other.effects.revealedUntil = now + ab.duration * 1000;
        }
      }
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type, duration: ab.duration });
      break;
    case "projectile": {
      const f = p.facing;
      const norm = Math.hypot(f.x, f.y) || 1;
      const fxn = f.x / norm, fyn = f.y / norm;
      state.projectiles.push({
        id: state.nextEntityId++,
        x: p.x + fxn * 25,
        y: p.y + fyn * 25,
        vx: fxn * ab.speed,
        vy: fyn * ab.speed,
        ownerId: p.id,
        damage: ab.damage,
        range: ab.range,
        dist: 0,
      });
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type, fx: fxn, fy: fyn });
      break;
    }
    case "teleport": {
      // Shadow Step now phases through walls and obstacles. Teleport to
      // the full distance, then if the landing point is inside a wall,
      // keep stepping forward until it isn't (so the killer always
      // emerges past the wall, never gets stuck inside it).
      const f = p.facing;
      const norm = Math.hypot(f.x, f.y) || 1;
      const fxn = f.x / norm, fyn = f.y / norm;
      const fromX = p.x, fromY = p.y;
      let tx = p.x + fxn * ab.distance;
      let ty = p.y + fyn * ab.distance;
      for (let i = 0; i < 24; i++) {
        if (!positionBlocked(tx, ty, 18)) break;
        tx += fxn * 6;
        ty += fyn * 6;
      }
      p.x = clamp(tx, 30, MAP.w - 30);
      p.y = clamp(ty, 30, MAP.h - 30);
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type, fromX, fromY, x: p.x, y: p.y });
      break;
    }
    case "buff_attack":
      p.effects.stalkUntil = now + ab.duration * 1000;
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type, duration: ab.duration });
      break;
    case "stun_burst": {
      // Instant AOE: slow any killer within radius.
      const affected = [];
      for (const k of state.players.values()) {
        if (k.role !== "killer" || !k.alive) continue;
        if (Math.hypot(k.x - p.x, k.y - p.y) <= ab.radius) {
          k.effects.slowMult = Math.min(k.effects.slowMult || 1, ab.slowMult);
          k.effects.slowUntil = Math.max(k.effects.slowUntil || 0, now + ab.duration * 1000);
          affected.push(k.id);
        }
      }
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type, x: p.x, y: p.y, radius: ab.radius, affected });
      break;
    }
    case "slow_field": {
      // Sentinel "summons" the field over channelDuration before it drops.
      // The location is captured at channel-end so the player can be repositioned.
      const channelMs = (ab.channelDuration || 0) * 1000;
      const ownerId = p.id;
      broadcast({ type: "ability_channel", id: ownerId, slot, abilityId: ab.id, abilityType: ab.type, duration: ab.channelDuration || 0 });
      setTimeout(() => {
        if (state.phase !== "playing") return;
        const owner = state.players.get(ownerId);
        if (!owner || !owner.alive) return;
        // Cap fields per Sentinel — pop the oldest if at the limit.
        const max = ab.maxFields || Infinity;
        const mine = state.slowFields.filter(f => f.ownerId === ownerId);
        if (mine.length >= max) {
          const oldest = mine[0];
          state.slowFields = state.slowFields.filter(f => f.id !== oldest.id);
          broadcast({ type: "field_break", fields: [{ id: oldest.id, x: oldest.x, y: oldest.y, radius: oldest.radius }], by: ownerId });
        }
        state.slowFields.push({
          id: state.nextEntityId++,
          x: owner.x, y: owner.y,
          radius: ab.radius,
          slowMult: ab.slowMult,
          ttl: ab.duration,
          ownerId,
        });
        broadcast({ type: "ability", id: ownerId, slot, abilityId: ab.id, abilityType: ab.type, x: owner.x, y: owner.y, radius: ab.radius });
      }, channelMs);
      break;
    }
    case "shoot_sniper": {
      // Consume 1 ammo. Spawn a projectile in the client-supplied aim direction.
      p.ammo = Math.max(0, (p.ammo || 0) - 1);
      const aim = (msg && msg.aim && typeof msg.aim.x === "number") ? msg.aim : p.facing;
      const aimNorm = Math.hypot(aim.x, aim.y) || 1;
      const fxn = aim.x / aimNorm, fyn = aim.y / aimNorm;
      state.projectiles.push({
        id: state.nextEntityId++,
        x: p.x + fxn * 22,
        y: p.y + fyn * 22,
        vx: fxn * ab.speed,
        vy: fyn * ab.speed,
        ownerId: p.id,
        range: ab.range,
        dist: 0,
        kind: "sniper",
        stunDuration: ab.stunDuration,
        hitRadius: ab.hitRadius || 22,
      });
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type, fx: fxn, fy: fyn });
      break;
    }
    case "sneak":
      p.effects.sneakUntil = now + ab.duration * 1000;
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type, duration: ab.duration });
      break;
    case "dash_strike":
      p.effects.speedMult = ab.speedMult;
      p.effects.speedUntil = now + ab.duration * 1000;
      p.effects.dashStrikeUntil = now + ab.duration * 1000;
      p.effects.dashHitDamage = ab.hitDamage;
      p.effects.dashHitSlowMult = ab.hitSlowMult;
      p.effects.dashHitSlowDuration = ab.hitSlowDuration;
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type, mult: ab.speedMult, duration: ab.duration });
      break;
    case "shield":
      p.effects.shieldUntil = now + ab.duration * 1000;
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type, duration: ab.duration });
      break;
    case "trap_fire": {
      if (p.form === "dino") {
        // FIRE!! — projectile that damages on hit.
        p.cooldowns[slot] = now + ab.fireCD * 1000;
        const f = p.facing;
        const norm = Math.hypot(f.x, f.y) || 1;
        const fxn = f.x / norm, fyn = f.y / norm;
        state.projectiles.push({
          id: state.nextEntityId++,
          x: p.x + fxn * 25, y: p.y + fyn * 25,
          vx: fxn * ab.fireSpeed, vy: fyn * ab.fireSpeed,
          ownerId: p.id,
          damage: ab.fireDamage,
          range: ab.fireRange,
          dist: 0,
          kind: "fire",
          hitRadius: 44,
        });
        broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: "fire", fx: fxn, fy: fyn });
      } else {
        // Trap — drop one at the killer's feet; cap to maxTraps per owner.
        p.cooldowns[slot] = now + ab.trapCD * 1000;
        const mine = state.traps.filter(t => t.ownerId === p.id);
        if (mine.length >= (ab.maxTraps || 3)) {
          const oldest = mine[0];
          state.traps = state.traps.filter(t => t.id !== oldest.id);
          broadcast({ type: "trap_break", id: oldest.id, x: oldest.x, y: oldest.y, evicted: true });
        }
        const trap = {
          id: state.nextEntityId++,
          x: p.x, y: p.y,
          ownerId: p.id,
          stunDuration: ab.trapStunDuration || 4,
          hitRadius: 22,
        };
        state.traps.push(trap);
        broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: "trap", x: trap.x, y: trap.y, trapId: trap.id });
      }
      break;
    }
    case "transform": {
      // 5s rooted channel, then form = "dino" for ab.duration seconds.
      const ownerId = p.id;
      const channelMs = (ab.channelDuration || 0) * 1000;
      broadcast({ type: "ability_channel", id: ownerId, slot, abilityId: ab.id, abilityType: ab.type, duration: ab.channelDuration });
      setTimeout(() => {
        if (state.phase !== "playing") return;
        const owner = state.players.get(ownerId);
        if (!owner || !owner.alive) return;
        owner.form = "dino";
        owner.formUntil = Date.now() + ab.duration * 1000;
        broadcast({ type: "form", id: ownerId, form: "dino", duration: ab.duration });
      }, channelMs);
      break;
    }
    case "spawn_robot": {
      // 3s rooted build channel, then a robot spawns at the Engineer's position.
      const ownerId = p.id;
      const channelMs = (ab.channelDuration || 0) * 1000;
      broadcast({ type: "ability_channel", id: ownerId, slot, abilityId: ab.id, abilityType: ab.type, duration: ab.channelDuration });
      setTimeout(() => {
        if (state.phase !== "playing") return;
        const owner = state.players.get(ownerId);
        if (!owner || !owner.alive) return;
        // Still only one robot allowed.
        if (state.robots.some(r => r.ownerId === ownerId)) return;
        const robot = {
          id: state.nextEntityId++,
          x: owner.x, y: owner.y,
          ownerId,
          ttl: ab.ttl || 40,
          speed: ab.speed || 230,
          hitRadius: ab.hitRadius || 25,
          stunDuration: ab.stunDuration || 12,
        };
        state.robots.push(robot);
        broadcast({ type: "ability", id: ownerId, slot, abilityId: ab.id, abilityType: ab.type, x: robot.x, y: robot.y, robotId: robot.id });
      }, channelMs);
      break;
    }
    case "throw_burger": {
      const f = p.facing;
      const norm = Math.hypot(f.x, f.y) || 1;
      const fxn = f.x / norm, fyn = f.y / norm;
      state.burgers.push({
        id: state.nextEntityId++,
        x: p.x + fxn * 22,
        y: p.y + fyn * 22,
        vx: fxn * ab.speed,
        vy: fyn * ab.speed,
        ownerId: p.id,
        healAmount: ab.healAmount,
        ttl: ab.ttl || 30,
        bounce: ab.bounce || 0.6,
      });
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type, fx: fxn, fy: fyn });
      break;
    }
    case "meow": {
      const R = ab.radius;
      for (const other of state.players.values()) {
        if (!other.alive) continue;
        if (Math.hypot(other.x - p.x, other.y - p.y) > R) continue;
        if (other.role === "survivor") {
          other.hp = Math.min(SURVIVOR_HP_MAX, other.hp + ab.healAmount);
          broadcast({ type: "heal", id: other.id, hp: Math.round(other.hp), by: p.id, amount: ab.healAmount });
        } else if (other.role === "killer") {
          other.effects.slowMult = Math.min(other.effects.slowMult || 1, ab.slowMult);
          other.effects.slowUntil = Math.max(other.effects.slowUntil || 0, now + ab.slowDuration * 1000);
        }
      }
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type, x: p.x, y: p.y, radius: R });
      break;
    }
    case "slash_stun": {
      // Single-target melee. The closest alive killer within range gets
      // stunned (slowMult = 0.05) for stunDuration seconds. No damage.
      let best = null, bestD = ab.range;
      for (const k of state.players.values()) {
        if (k.role !== "killer" || !k.alive) continue;
        const d = Math.hypot(k.x - p.x, k.y - p.y);
        if (d < bestD) { bestD = d; best = k; }
      }
      if (best) {
        best.effects.slowMult = 0.05;
        best.effects.slowUntil = Math.max(best.effects.slowUntil || 0, now + ab.stunDuration * 1000);
        broadcast({ type: "stun", id: best.id, by: p.id, duration: ab.stunDuration });
      }
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type });
      break;
    }
    case "build_portal": {
      // 4s rooted channel, then drop a portal at the killer's position.
      const ownerId = p.id;
      const channelMs = (ab.channelDuration || 0) * 1000;
      broadcast({ type: "ability_channel", id: ownerId, slot, abilityId: ab.id, abilityType: ab.type, duration: ab.channelDuration });
      setTimeout(() => {
        if (state.phase !== "playing") return;
        const owner = state.players.get(ownerId);
        if (!owner || !owner.alive || owner.role !== "killer") return;
        const max = ab.maxPortals || Infinity;
        if (state.portals.length >= max) {
          const oldest = state.portals.shift();
          broadcast({ type: "portal_break", id: oldest.id, x: oldest.x, y: oldest.y });
        }
        const portal = { id: state.nextEntityId++, x: owner.x, y: owner.y, ownerId };
        state.portals.push(portal);
        broadcast({ type: "ability", id: ownerId, slot, abilityId: ab.id, abilityType: ab.type, x: portal.x, y: portal.y, portalId: portal.id });
      }, channelMs);
      break;
    }
    case "teleport_portal": {
      // Client supplied msg.portalId. Validate, channel, then teleport.
      const portalId = (msg && (msg.portalId | 0)) || 0;
      const portal = state.portals.find(pt => pt.id === portalId);
      if (!portal) return;
      const ownerId = p.id;
      const channelMs = (ab.channelDuration || 0) * 1000;
      broadcast({ type: "ability_channel", id: ownerId, slot, abilityId: ab.id, abilityType: ab.type, duration: ab.channelDuration });
      setTimeout(() => {
        if (state.phase !== "playing") return;
        const owner = state.players.get(ownerId);
        if (!owner || !owner.alive) return;
        const pt = state.portals.find(p => p.id === portalId);
        if (!pt) return;     // portal got replaced during channel
        const fromX = owner.x, fromY = owner.y;
        owner.x = pt.x; owner.y = pt.y;
        broadcast({ type: "ability", id: ownerId, slot, abilityId: ab.id, abilityType: ab.type, fromX, fromY, x: owner.x, y: owner.y });
      }, channelMs);
      break;
    }
    case "reload_sniper":
      p.reloadUntil = now + ab.reloadDuration * 1000;
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type, duration: ab.reloadDuration });
      break;
    case "stab": {
      // Angel's dagger: closest alive killer within range gets stunned, no
      // damage. Malice gain is doubled if Angel is currently ducking.
      let best = null, bestD = ab.range;
      for (const k of state.players.values()) {
        if (k.role !== "killer" || !k.alive) continue;
        const d = Math.hypot(k.x - p.x, k.y - p.y);
        if (d < bestD) { bestD = d; best = k; }
      }
      const wasDucking = now < (p.effects.duckUntil || 0);
      if (best) {
        best.effects.slowMult = 0.05;
        best.effects.slowUntil = Math.max(best.effects.slowUntil || 0, now + ab.stunDuration * 1000);
        broadcast({ type: "stun", id: best.id, by: p.id, duration: ab.stunDuration });
        // Malice stops accumulating once Angel has burned the respawn —
        // the passive is one-shot per round so there's no second life to
        // earn a second time.
        if (!p.respawned) {
          const gain = wasDucking ? (ab.maliceGainDuck || ab.maliceGain) : ab.maliceGain;
          p.malice = Math.min(100, (p.malice || 0) + gain);
        }
      }
      // Stab always reveals Angel — Duck ends immediately, hit or miss.
      if (wasDucking) {
        p.effects.duckUntil = 0;
        p.effects.sneakUntil = 0;
      }
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type });
      break;
    }
    case "duck":
      // 95% invisible (shares the sneak visibility path) + flag that Angel is
      // ducking so the next Stab counts double. Self-slow is applied client-side.
      p.effects.sneakUntil = now + ab.duration * 1000;
      p.effects.duckUntil  = now + ab.duration * 1000;
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type, duration: ab.duration, speedMult: ab.speedMult });
      break;
    case "heal_self_instant": {
      // Pollen's Breathe — top up HP immediately.
      p.hp = Math.min(SURVIVOR_HP_MAX, p.hp + (ab.amount || 0));
      broadcast({ type: "heal", id: p.id, hp: Math.round(p.hp), by: p.id, amount: ab.amount });
      broadcast({ type: "ability", id: p.id, slot, abilityId: ab.id, abilityType: ab.type });
      break;
    }
    case "build_station": {
      // 5s rooted channel. HP cost is paid up front so a cancelled / killed
      // channel still spends it (commitment). At channel end, drop a station
      // at the caster's position. Cap: one station per kind per caster —
      // re-casting replaces the old one.
      const ownerId = p.id;
      const cost = ab.hpCost || 0;
      if (cost) {
        applyDamage(p, cost, p);
        if (!p.alive) return; // sacrifice killed her — no station drops
      }
      const channelMs = (ab.channelDuration || 0) * 1000;
      broadcast({ type: "ability_channel", id: ownerId, slot, abilityId: ab.id, abilityType: ab.type, duration: ab.channelDuration });
      setTimeout(() => {
        if (state.phase !== "playing") return;
        const owner = state.players.get(ownerId);
        if (!owner || !owner.alive) return;
        // Drop one of this kind per owner.
        state.stations = state.stations.filter(st => !(st.ownerId === ownerId && st.kind === ab.stationKind));
        const st = {
          id: state.nextEntityId++,
          x: owner.x, y: owner.y,
          ownerId,
          kind: ab.stationKind,
          radius: ab.radius || 140,
          healPerSec:   ab.healPerSec   || 0,
          shieldDuration: ab.shieldDuration || 0,
        };
        state.stations.push(st);
        broadcast({ type: "ability", id: ownerId, slot, abilityId: ab.id, abilityType: ab.type, x: st.x, y: st.y, stationId: st.id, kind: st.kind });
      }, channelMs);
      break;
    }
    case "spawn_pad": {
      // 3s rooted channel, then a spawn pad drops at Angel's position. One
      // pad per Angel — slot also has maxUses: 1 so it locks after firing.
      const ownerId = p.id;
      const channelMs = (ab.channelDuration || 0) * 1000;
      broadcast({ type: "ability_channel", id: ownerId, slot, abilityId: ab.id, abilityType: ab.type, duration: ab.channelDuration });
      setTimeout(() => {
        if (state.phase !== "playing") return;
        const owner = state.players.get(ownerId);
        if (!owner || !owner.alive) return;
        // Replace any existing pad for this Angel.
        state.spawnPads = state.spawnPads.filter(sp => sp.ownerId !== ownerId);
        const pad = { id: state.nextEntityId++, x: owner.x, y: owner.y, ownerId };
        state.spawnPads.push(pad);
        broadcast({ type: "ability", id: ownerId, slot, abilityId: ab.id, abilityType: ab.type, x: pad.x, y: pad.y, padId: pad.id });
      }, channelMs);
      break;
    }
  }
}

function onSkill(id, msg) {
  if (state.phase !== "playing") return;
  const p = state.players.get(id);
  if (!p || p.role !== "survivor" || !p.alive) return;
  const idx = msg.gen;
  if (typeof idx !== "number" || idx < 0 || idx >= state.generators.length) return;
  const g = state.generators[idx];
  if (g.done) return;
  if (Math.hypot(p.x - g.x, p.y - g.y) > SKILL_NEAR_RADIUS) return;
  const now = Date.now();
  const last = state.lastSkill.get(id) || 0;
  if (now - last < SKILL_COOLDOWN_MS) return;
  state.lastSkill.set(id, now);
  const result = msg.result === "green" || msg.result === "yellow" ? msg.result : "red";
  let delta = SKILL_PROGRESS[result];
  if (delta > 0) {
    const sc = survivorCharOf(p);
    delta *= sc.repairMult;
  }
  g.progress = Math.max(0, Math.min(1, g.progress + delta));
  if (g.progress >= 1) {
    g.progress = 1; g.done = true;
    state.roundTimer = Math.max(0, state.roundTimer + TIME_PER_GEN);
    broadcast({ type: "gen_done", indices: [idx], timer: state.roundTimer });
    if (state.roundTimer <= 0) endRound("survivors");
  }
}

function startRound() {
  // Pick the round's map FIRST so freshGens() reads the right pool and
  // every helper using WALLS/OBSTACLES/CONVEYORS sees the right set.
  // Host's lobby selection wins; "random" (or anything unknown) rolls.
  const picked = state.selectedMap;
  state.currentMap = (picked && MAP_IDS.includes(picked))
    ? picked
    : MAP_IDS[Math.floor(Math.random() * MAP_IDS.length)];
  WALLS     = MAPS[state.currentMap].walls;
  OBSTACLES = MAPS[state.currentMap].obstacles;
  GEN_POOL  = MAPS[state.currentMap].gens;
  CONVEYORS = MAPS[state.currentMap].conveyors || [];

  state.generators = freshGens();
  state.roundTimer = ROUND_DURATION;
  state.winner = null;
  state.lmsTriggered = false;
  state.lastSkill.clear();
  state.projectiles = [];
  state.smokes = [];
  state.slowFields = [];
  state.portals = [];
  state.burgers = [];
  state.robots = [];
  state.traps = [];
  state.spawnPads = [];
  state.clovers = [];
  state.stations = [];

  const killerId = state.designatedKillerId;
  const survIds = [...state.players.keys()].filter(pid => pid !== killerId);
  state.survivorStartCount = survIds.length;

  const killer = state.players.get(killerId);
  const kch = killerCharOf(killer);
  killer.role = "killer";
  killer.color = kch.color;
  killer.x = MAP.w / 2;
  killer.y = 220;
  killer.alive = true;
  killer.hp = SURVIVOR_HP_MAX; // unused for killer
  killer.facing = { x: 1, y: 0 };
  killer.cooldowns = [0, 0, 0];
  killer.mainAttackCdUntil = 0;
  killer.ammo = 1; killer.reloadUntil = 0;
  killer.abilityUses = {};
  killer.form = "human";        // Sly starts human each round; reset for everyone
  killer.formUntil = 0;
  killer.effects = freshEffects();

  survIds.forEach((sid, idx) => {
    const p = state.players.get(sid);
    const sch = survivorCharOf(p);
    p.role = "survivor";
    p.color = sch.color;
    p.x = MAP.w / 2 + (idx - (survIds.length - 1) / 2) * 80;
    p.y = MAP.h - 220;
    p.alive = true;
    p.hp = SURVIVOR_HP_MAX;
    p.facing = { x: 1, y: 0 };
    p.cooldowns = [0, 0, 0];
    p.mainAttackCdUntil = 0;
    p.ammo = 1; p.reloadUntil = 0;
    p.abilityUses = {};
    p.effects = freshEffects();
    p.malice = 0;
    p.respawned = false;
    p._lastCloverX = null; p._lastCloverY = null;
  });

  state.phase = "playing";
  broadcast({
    type: "start",
    players: serializePlayers(),
    gens: state.generators,
    roundDuration: ROUND_DURATION,
    timer: state.roundTimer,
    mapId: state.currentMap,
  });
}

function checkRoundEnd() {
  if (state.phase !== "playing") return;
  let anyActive = false, anySurv = false, aliveCount = 0;
  for (const p of state.players.values()) {
    if (p.role !== "survivor") continue;
    anySurv = true;
    if (p.alive) { anyActive = true; aliveCount++; }
  }
  if (!anySurv) return;
  if (!anyActive) { endRound("killer"); return; }
  // Last-Man-Standing: exactly one survivor left, the round started with
  // at least two, and we haven't already triggered it.
  if (!state.lmsTriggered && aliveCount === 1 && (state.survivorStartCount || 0) >= 2) {
    state.lmsTriggered = true;
    state.roundTimer = 60;
    const killer = [...state.players.values()].find(p => p.role === "killer" && p.alive);
    broadcast({
      type: "lms",
      killerChar: killer ? killer.killerChar : "slasher",
      timer: state.roundTimer,
    });
  }
}

function endRound(winner) {
  if (state.phase !== "playing") return;
  state.phase = "over";
  state.winner = winner;
  state.resetAt = Date.now() + RESULT_HOLD_MS;
  broadcast({ type: "over", winner });
}

let lastTickTime = Date.now();
function tick() {
  const now = Date.now();
  const dt = (now - lastTickTime) / 1000;
  lastTickTime = now;

  if (state.phase === "playing") {
    state.roundTimer = Math.max(0, state.roundTimer - dt);

    // Heal ticks
    for (const p of state.players.values()) {
      if (p.role !== "survivor" || !p.alive) continue;
      if (now < p.effects.healUntil) {
        p.hp = Math.min(SURVIVOR_HP_MAX, p.hp + p.effects.healRate * dt);
      }
    }

    // Slow-field sustained effect on killers standing in a field.
    for (const k of state.players.values()) {
      if (k.role !== "killer" || !k.alive) continue;
      // Reset stale slow first — previous stun_burst values shouldn't
      // bleed forward and clobber a weaker field slow.
      if (now >= k.effects.slowUntil) k.effects.slowMult = 1;
      let bestSlow = 1;
      for (const f of state.slowFields) {
        if (Math.hypot(k.x - f.x, k.y - f.y) <= f.radius) {
          if (f.slowMult < bestSlow) bestSlow = f.slowMult;
        }
      }
      if (bestSlow < 1) {
        k.effects.slowMult = Math.min(k.effects.slowMult, bestSlow);
        // Slow lingers ~5s after leaving the field.
        k.effects.slowUntil = Math.max(k.effects.slowUntil, now + 5000);
      }
    }

    // Smoke conceals survivors from the killer.
    for (const p of state.players.values()) {
      if (p.role !== "survivor") { p.hiddenInSmoke = false; continue; }
      p.hiddenInSmoke = false;
      for (const sm of state.smokes) {
        if (Math.hypot(p.x - sm.x, p.y - sm.y) <= sm.radius) {
          p.hiddenInSmoke = true;
          break;
        }
      }
    }

    // Decay slow fields
    for (const f of state.slowFields) f.ttl -= dt;
    state.slowFields = state.slowFields.filter(f => f.ttl > 0);

    // Projectiles. Sub-step so fast bullets don't tunnel through 30px walls.
    const survivors = [...state.players.values()].filter(p => p.role === "survivor" && p.alive);
    const killers   = [...state.players.values()].filter(p => p.role === "killer"   && p.alive);
    const projHits = [];
    const broken = [];
    const STEPS = 5;
    state.projectiles = state.projectiles.filter(pr => {
      const sx = pr.vx * dt / STEPS;
      const sy = pr.vy * dt / STEPS;
      const stepLen = Math.hypot(sx, sy);
      for (let i = 0; i < STEPS; i++) {
        pr.x += sx; pr.y += sy; pr.dist += stepLen;
        if (pr.dist > pr.range) return false;
        if (pr.x < 0 || pr.x > MAP.w || pr.y < 0 || pr.y > MAP.h) return false;
        if (pr.kind === "sniper") {
          // Bullet breaks on the first wall or obstacle.
          for (const w of WALLS) {
            if (pointInRect(pr.x, pr.y, w)) {
              broken.push({ id: pr.id, x: pr.x, y: pr.y });
              return false;
            }
          }
          for (const o of OBSTACLES) {
            if (pointInRect(pr.x, pr.y, o)) {
              broken.push({ id: pr.id, x: pr.x, y: pr.y });
              return false;
            }
          }
          // Stun the killer on hit (no damage).
          const HIT = pr.hitRadius || 22;
          for (const k of killers) {
            if (Math.hypot(k.x - pr.x, k.y - pr.y) < HIT) {
              k.effects.slowMult = 0.05;
              k.effects.slowUntil = Math.max(k.effects.slowUntil || 0, Date.now() + pr.stunDuration * 1000);
              broadcast({ type: "stun", id: k.id, by: pr.ownerId, duration: pr.stunDuration });
              return false;
            }
          }
        } else {
          // Throw Knife (Slasher): hits survivors.
          for (const s of survivors) {
            if (Math.hypot(s.x - pr.x, s.y - pr.y) < 22) {
              const att = state.players.get(pr.ownerId);
              if (att) projHits.push({ s, dmg: pr.damage, att });
              return false;
            }
          }
        }
      }
      return true;
    });
    for (const h of projHits) applyDamage(h.s, h.dmg, h.att);
    if (broken.length > 0) broadcast({ type: "projectile_break", projectiles: broken });

    // Lunar dash collision: first survivor within 30 px of a dashing
    // killer takes hitDamage + a slow, then the dash ends (both the
    // strike window and the speed boost — the dash is "spent" on hit).
    for (const k of state.players.values()) {
      if (k.role !== "killer" || !k.alive) continue;
      if (!k.effects.dashStrikeUntil || now >= k.effects.dashStrikeUntil) continue;
      for (const s of state.players.values()) {
        if (s.role !== "survivor" || !s.alive) continue;
        if (Math.hypot(s.x - k.x, s.y - k.y) < 30) {
          applyDamage(s, k.effects.dashHitDamage || 30, k);
          s.effects.slowMult = Math.min(s.effects.slowMult || 1, k.effects.dashHitSlowMult || 0.7);
          s.effects.slowUntil = Math.max(s.effects.slowUntil || 0, now + (k.effects.dashHitSlowDuration || 3) * 1000);
          k.effects.dashStrikeUntil = 0;
          k.effects.speedUntil = 0;     // end the dash's speed boost too
          k.effects.speedMult  = 1;
          broadcast({ type: "dash_hit", id: s.id, by: k.id, x: s.x, y: s.y });
          break;
        }
      }
    }

    // Convey-on-tick helper: any entity within a CONVEYORS rect gets
    // pushed by that belt's (vx, vy). Used for server-owned entities
    // (robots, burgers). Players push themselves client-side.
    const applyConveyor = (e, dt2) => {
      for (const c of CONVEYORS) {
        if (pointInRect(e.x, e.y, c)) {
          e.x += c.vx * dt2;
          e.y += c.vy * dt2;
          return;
        }
      }
    };

    // Engineer robots: walk toward the killer at their configured speed,
    // stun on contact, despawn after TTL or contact.
    state.robots = state.robots.filter(r => {
      r.ttl -= dt;
      if (r.ttl <= 0) {
        broadcast({ type: "robot_break", id: r.id, x: r.x, y: r.y, expired: true });
        return false;
      }
      let killer = null;
      for (const p of state.players.values()) {
        if (p.role === "killer" && p.alive) { killer = p; break; }
      }
      if (killer) {
        const dxk = killer.x - r.x, dyk = killer.y - r.y;
        const dk = Math.hypot(dxk, dyk);
        if (dk > 0.5) {
          const nx = dxk / dk, ny = dyk / dk;
          const step = r.speed * dt;
          const tx = r.x + nx * step;
          const ty = r.y + ny * step;
          // Move axis-by-axis so walls don't fully stop motion when the
          // straight path is blocked.
          if (!positionBlocked(tx, r.y, 12)) r.x = tx;
          if (!positionBlocked(r.x, ty, 12)) r.y = ty;
        }
        // Conveyors carry the robot too.
        applyConveyor(r, dt);
        if (Math.hypot(r.x - killer.x, r.y - killer.y) < r.hitRadius) {
          killer.effects.slowMult = 0.05;
          killer.effects.slowUntil = Math.max(killer.effects.slowUntil || 0, Date.now() + r.stunDuration * 1000);
          broadcast({ type: "stun", id: killer.id, by: r.ownerId, duration: r.stunDuration });
          broadcast({ type: "robot_break", id: r.id, x: r.x, y: r.y, hit: true });
          return false;
        }
      }
      return true;
    });

    // Sly traps: any survivor stepping on one gets stunned and the trap breaks.
    state.traps = state.traps.filter(tr => {
      for (const s of state.players.values()) {
        if (s.role !== "survivor" || !s.alive) continue;
        if (Math.hypot(s.x - tr.x, s.y - tr.y) < (tr.hitRadius || 22)) {
          s.effects.slowMult = 0.05;
          s.effects.slowUntil = Math.max(s.effects.slowUntil || 0, Date.now() + tr.stunDuration * 1000);
          broadcast({ type: "stun", id: s.id, by: tr.ownerId, duration: tr.stunDuration });
          broadcast({ type: "trap_break", id: tr.id, x: tr.x, y: tr.y, by: s.id });
          return false;
        }
      }
      return true;
    });

    // Pollen passive: drop a clover every CLOVER_SPACING px traveled
    // since the last drop. Clovers live for CLOVER_TTL seconds and heal
    // 0.5 HP/s to any OTHER survivor standing on them.
    const CLOVER_SPACING = 32;
    const CLOVER_TTL = 2.5;     // short trail — fades quickly
    const CLOVER_R = 16;
    const CLOVER_HEAL_PER_SEC = 0.5;
    const CLOVER_MAX_PER_OWNER = 40;
    for (const p of state.players.values()) {
      if (p.survivorChar !== "pollen" || p.role !== "survivor" || !p.alive) continue;
      if (p._lastCloverX == null) {
        p._lastCloverX = p.x; p._lastCloverY = p.y;
        state.clovers.push({ id: state.nextEntityId++, x: p.x, y: p.y, ownerId: p.id, ttl: CLOVER_TTL });
      }
      const dist = Math.hypot(p.x - p._lastCloverX, p.y - p._lastCloverY);
      if (dist >= CLOVER_SPACING) {
        p._lastCloverX = p.x; p._lastCloverY = p.y;
        // Cap so the trail stays "short" — drop oldest if over budget.
        const mine = state.clovers.filter(cv => cv.ownerId === p.id);
        if (mine.length >= CLOVER_MAX_PER_OWNER) {
          const oldest = mine[0];
          state.clovers = state.clovers.filter(cv => cv.id !== oldest.id);
        }
        state.clovers.push({ id: state.nextEntityId++, x: p.x, y: p.y, ownerId: p.id, ttl: CLOVER_TTL });
      }
    }
    // Decay clovers + heal other survivors standing on at least one.
    for (const cv of state.clovers) cv.ttl -= dt;
    state.clovers = state.clovers.filter(cv => cv.ttl > 0);
    for (const s of state.players.values()) {
      if (s.role !== "survivor" || !s.alive) continue;
      if (s.hp >= SURVIVOR_HP_MAX) continue;
      let onClover = false;
      for (const cv of state.clovers) {
        if (cv.ownerId === s.id) continue; // can't heal off your own trail
        if (Math.hypot(s.x - cv.x, s.y - cv.y) < CLOVER_R) { onClover = true; break; }
      }
      if (onClover) {
        s.hp = Math.min(SURVIVOR_HP_MAX, s.hp + CLOVER_HEAL_PER_SEC * dt);
      }
    }

    // Pollen stations: heal or refresh shields on nearby survivors.
    for (const st of state.stations) {
      for (const s of state.players.values()) {
        if (s.role !== "survivor" || !s.alive) continue;
        if (Math.hypot(s.x - st.x, s.y - st.y) > st.radius) continue;
        if (st.kind === "heal") {
          if (s.hp < SURVIVOR_HP_MAX) {
            s.hp = Math.min(SURVIVOR_HP_MAX, s.hp + (st.healPerSec || 0) * dt);
          }
        } else if (st.kind === "defence") {
          const want = Date.now() + (st.shieldDuration || 0) * 1000;
          if ((s.effects.shieldUntil || 0) < want) s.effects.shieldUntil = want;
        }
      }
    }

    // Sly form auto-revert: when formUntil expires, drop back to "human".
    for (const p of state.players.values()) {
      if (p.role !== "killer") continue;
      if (p.form === "dino" && p.formUntil && Date.now() >= p.formUntil) {
        p.form = "human";
        p.formUntil = 0;
        broadcast({ type: "form", id: p.id, form: "human" });
      }
    }

    // Portal step pings: any portal with a survivor on it pings the killer.
    const portalsActive = [];
    for (const pt of state.portals) {
      for (const s of state.players.values()) {
        if (s.role !== "survivor" || !s.alive) continue;
        if (Math.hypot(s.x - pt.x, s.y - pt.y) < 40) {
          portalsActive.push(pt.id);
          break;
        }
      }
    }
    state._portalsActiveSnapshot = portalsActive;

    // Reload completion (sniper).
    for (const p of state.players.values()) {
      if (p.reloadUntil && now >= p.reloadUntil) {
        p.ammo = 1;
        p.reloadUntil = 0;
      }
    }

    // Smokes
    for (const sm of state.smokes) sm.ttl -= dt;
    state.smokes = state.smokes.filter(sm => sm.ttl > 0);

    // Burgers (Kacey): move with friction, bounce off walls/obstacles,
    // get eaten by any other survivor, despawn after TTL.
    const BURGER_R = 10;
    const FRICTION_PER_SEC = 0.3; // multiplier per second
    const fric = Math.pow(FRICTION_PER_SEC, dt);
    const burgerHit = (b, rect) => {
      const wl = rect.x - rect.w / 2, wr = rect.x + rect.w / 2;
      const wt = rect.y - rect.h / 2, wb = rect.y + rect.h / 2;
      if (b.x + BURGER_R <= wl || b.x - BURGER_R >= wr) return false;
      if (b.y + BURGER_R <= wt || b.y - BURGER_R >= wb) return false;
      const penX = Math.min(b.x + BURGER_R - wl, wr - (b.x - BURGER_R));
      const penY = Math.min(b.y + BURGER_R - wt, wb - (b.y - BURGER_R));
      if (penX < penY) {
        if (b.x < rect.x) b.x = wl - BURGER_R; else b.x = wr + BURGER_R;
        b.vx = -b.vx * b.bounce;
      } else {
        if (b.y < rect.y) b.y = wt - BURGER_R; else b.y = wb + BURGER_R;
        b.vy = -b.vy * b.bounce;
      }
      return true;
    };
    state.burgers = state.burgers.filter(b => {
      b.ttl -= dt;
      if (b.ttl <= 0) return false;
      b.x += b.vx * dt;
      b.y += b.vy * dt;
      b.vx *= fric; b.vy *= fric;
      applyConveyor(b, dt);
      if (Math.abs(b.vx) < 2) b.vx = 0;
      if (Math.abs(b.vy) < 2) b.vy = 0;
      for (const w of WALLS) burgerHit(b, w);
      for (const o of OBSTACLES) burgerHit(b, o);
      // Map bounds
      if (b.x < BURGER_R)            { b.x = BURGER_R;            b.vx = -b.vx * b.bounce; }
      if (b.x > MAP.w - BURGER_R)    { b.x = MAP.w - BURGER_R;    b.vx = -b.vx * b.bounce; }
      if (b.y < BURGER_R)            { b.y = BURGER_R;            b.vy = -b.vy * b.bounce; }
      if (b.y > MAP.h - BURGER_R)    { b.y = MAP.h - BURGER_R;    b.vy = -b.vy * b.bounce; }
      // Pickup by any other living survivor
      for (const s of state.players.values()) {
        if (s.role !== "survivor" || !s.alive) continue;
        if (s.id === b.ownerId) continue;
        if (Math.hypot(s.x - b.x, s.y - b.y) < 22) {
          const before = s.hp;
          s.hp = Math.min(SURVIVOR_HP_MAX, s.hp + b.healAmount);
          broadcast({ type: "heal", id: s.id, hp: Math.round(s.hp), amount: s.hp - before });
          broadcast({ type: "burger_eat", id: b.id, x: b.x, y: b.y, by: s.id });
          return false;
        }
      }
      return true;
    });

    if (state.roundTimer <= 0) {
      endRound("survivors");
    } else {
      broadcast({
        type: "state",
        timer: +state.roundTimer.toFixed(2),
        players: [...state.players.values()].map(p => ({
          id: p.id, x: Math.round(p.x), y: Math.round(p.y),
          fx: +p.facing.x.toFixed(2), fy: +p.facing.y.toFixed(2),
          alive: p.alive,
          hp: p.role === "survivor" ? Math.round(p.hp) : null,
          se: now < p.effects.speedUntil ? 1 : 0,
          st: now < p.effects.stalkUntil ? 1 : 0,
          re: now < p.effects.revealedUntil ? 1 : 0,
          sn: now < (p.effects.sneakUntil || 0) ? 1 : 0,
          hd: p.role === "survivor" && p.hiddenInSmoke ? 1 : 0,
          sm: now < (p.effects.slowUntil || 0) ? +(p.effects.slowMult || 1).toFixed(2) : 1,
          sh: now < (p.effects.shieldUntil || 0) ? 1 : 0,
          fm: p.form === "dino" ? 1 : 0,
          du: now < (p.effects.duckUntil || 0) ? 1 : 0,
          ml: p.role === "survivor" && p.survivorChar === "angel" ? Math.round(p.malice || 0) : 0,
          wg: p.respawned ? 1 : 0,
          am: p.ammo || 0,
          rl: p.reloadUntil || 0,
        })),
        progress: state.generators.map(g => +g.progress.toFixed(3)),
        projectiles: state.projectiles.map(pr => ({
          id: pr.id, x: Math.round(pr.x), y: Math.round(pr.y),
          vx: +pr.vx.toFixed(1), vy: +pr.vy.toFixed(1),
          k: pr.kind || null,
        })),
        smokes: state.smokes.map(sm => ({
          id: sm.id, x: sm.x, y: sm.y, radius: sm.radius, ttl: +sm.ttl.toFixed(2),
        })),
        slowFields: state.slowFields.map(f => ({
          id: f.id, x: f.x, y: f.y, radius: f.radius, ttl: +f.ttl.toFixed(2),
        })),
        portals: state.portals.map(pt => ({ id: pt.id, x: pt.x, y: pt.y })),
        portalsActive: state._portalsActiveSnapshot || [],
        burgers: state.burgers.map(b => ({
          id: b.id,
          x: Math.round(b.x), y: Math.round(b.y),
          vx: +b.vx.toFixed(1), vy: +b.vy.toFixed(1),
        })),
        robots: state.robots.map(r => ({ id: r.id, x: Math.round(r.x), y: Math.round(r.y) })),
        traps:  state.traps.map(t  => ({ id: t.id, x: Math.round(t.x), y: Math.round(t.y) })),
        spawnPads: state.spawnPads.map(sp => ({ id: sp.id, x: sp.x, y: sp.y, ownerId: sp.ownerId })),
        clovers: state.clovers.map(cv => ({ id: cv.id, x: Math.round(cv.x), y: Math.round(cv.y), o: cv.ownerId, t: +cv.ttl.toFixed(2) })),
        stations: state.stations.map(st => ({ id: st.id, x: st.x, y: st.y, ownerId: st.ownerId, kind: st.kind, radius: st.radius })),
      });
    }
  } else if (state.phase === "over" && now >= state.resetAt) {
    state.phase = "lobby";
    state.generators = freshGens();
    state.roundTimer = ROUND_DURATION;
    state.projectiles = [];
    state.smokes = [];
    state.slowFields = [];
    state.portals = [];
    state.burgers = [];
    state.robots = [];
    state.traps = [];
    state.spawnPads = [];
    state.clovers = [];
    state.stations = [];
    for (const p of state.players.values()) {
      p.role = "unassigned";
      p.alive = true;
      p.hp = SURVIVOR_HP_MAX;
      p.cooldowns = [0, 0, 0];
      p.effects = freshEffects();
      p.malice = 0;
      p.respawned = false;
      p._lastCloverX = null; p._lastCloverY = null;
      const sc = SURVIVOR_CHARS.find(c => c.id === p.survivorChar);
      if (sc) p.color = sc.color;
    }
    broadcastLobby();
  }
}

function broadcastLobby() {
  broadcast({
    type: "lobby",
    phase: state.phase,
    players: serializePlayers(),
    designatedKillerId: state.designatedKillerId,
    randomKillerEnabled: state.randomKillerEnabled,
    selectedMap: state.selectedMap,
    mapIds: MAP_IDS,
  });
}

function serializePlayers() {
  return [...state.players.values()].map(p => ({
    id: p.id, name: p.name, color: p.color,
    role: p.role, isHost: p.isHost,
    x: Math.round(p.x), y: Math.round(p.y),
    alive: p.alive,
    hp: p.role === "survivor" ? Math.round(p.hp) : null,
    survivorChar: p.survivorChar,
    killerChar: p.killerChar,
  }));
}

function broadcast(msg) {
  const json = JSON.stringify(msg);
  for (const ws of wss.clients) {
    if (ws.readyState === 1) { try { ws.send(json); } catch {} }
  }
}
function send(ws, msg) {
  if (ws.readyState !== 1) return;
  try { ws.send(JSON.stringify(msg)); } catch {}
}
function survivorCharOf(p) {
  return SURVIVOR_CHARS.find(c => c.id === p.survivorChar) || SURVIVOR_CHARS[0];
}
function killerCharOf(p) {
  return KILLER_CHARS.find(c => c.id === p.killerChar) || KILLER_CHARS[0];
}
function clamp(v, lo, hi) { return v < lo ? lo : v > hi ? hi : v; }

setInterval(tick, TICK_MS);
server.listen(PORT, () => {
  console.log(`Forsaken server listening on :${PORT}`);
});
  // =================== end server.js (verbatim) ===================

  // Add a participant: returns their fake server-side socket. Calling code
  // wires sw.onOut (server→participant) and sw.emit("message", json) (participant→server).
  function makeConn() {
    var sw = new FakeServerWS();
    __wss.clients.add(sw);
    if (__wss._h.connection) __wss._h.connection(sw);
    return sw;
  }
  // Expose the authoritative wall/obstacle collision test (uses the current
  // map's geometry, swapped on round start) so bots can avoid walls.
  window.__ForsakenSolo = {
    makeConn: makeConn,
    blocked: function (x, y, r) { return positionBlocked(x, y, r); },
    mapSize: function () { return { w: MAP.w, h: MAP.h }; },
  };
})();
